using System.Diagnostics.Metrics;

namespace QuantEngine.Host.Metrics;

/// <summary>
/// Central metrics registry using System.Diagnostics.Metrics (built-in .NET 8).
/// Counters/histograms can be consumed by OpenTelemetry, dotnet-counters, or Prometheus exporters.
/// Usage: dotnet-counters monitor --name QuantEngine --counters QuantEngine
/// </summary>
public static class QuantEngineMetrics
{
    private static readonly Meter Meter = new("QuantEngine", "1.0.0");

    // ── Backtest metrics ──────────────────────────────────────────────────────
    /// <summary>Total completed backtest runs since process start.</summary>
    public static readonly Counter<long> BacktestRuns =
        Meter.CreateCounter<long>("backtest.runs",
            description: "Total completed backtest runs");

    /// <summary>Duration in milliseconds for each backtest run.</summary>
    public static readonly Histogram<double> BacktestDurationMs =
        Meter.CreateHistogram<double>("backtest.duration_ms", unit: "ms",
            description: "Backtest execution time in milliseconds");

    // ── Trade metrics ─────────────────────────────────────────────────────────
    /// <summary>Total trades executed (backtest or live).</summary>
    public static readonly Counter<long> TradesTotal =
        Meter.CreateCounter<long>("trades.total",
            description: "Total trades across all runs");

    /// <summary>Winning trades count.</summary>
    public static readonly Counter<long> TradesWon =
        Meter.CreateCounter<long>("trades.won",
            description: "Winning trades");

    /// <summary>Losing trades count.</summary>
    public static readonly Counter<long> TradesLost =
        Meter.CreateCounter<long>("trades.lost",
            description: "Losing trades");

    // ── Signal metrics ────────────────────────────────────────────────────────
    /// <summary>Total entry signals generated.</summary>
    public static readonly Counter<long> SignalsGenerated =
        Meter.CreateCounter<long>("signals.generated",
            description: "Entry signals generated by AlphaScorer");

    // ── Live trading metrics ──────────────────────────────────────────────────
    /// <summary>Orders placed via broker APIs.</summary>
    public static readonly Counter<long> OrdersPlaced =
        Meter.CreateCounter<long>("orders.placed",
            description: "Orders submitted to broker");

    /// <summary>Orders rejected by pre-trade risk check or broker.</summary>
    public static readonly Counter<long> OrdersRejected =
        Meter.CreateCounter<long>("orders.rejected",
            description: "Orders rejected (risk or broker)");

    /// <summary>Current open position count gauge (use UpDownCounter for live tracking).</summary>
    public static readonly UpDownCounter<int> OpenPositions =
        Meter.CreateUpDownCounter<int>("positions.open",
            description: "Current count of open positions");

    // ── Data metrics ──────────────────────────────────────────────────────────
    /// <summary>Yahoo Finance API calls made.</summary>
    public static readonly Counter<long> YahooApiCalls =
        Meter.CreateCounter<long>("data.yahoo_calls",
            description: "Yahoo Finance v8 API requests");

    /// <summary>Cache hits that avoided a Yahoo API call.</summary>
    public static readonly Counter<long> CacheHits =
        Meter.CreateCounter<long>("data.cache_hits",
            description: "OHLC disk-cache hits");

    // ── Error metrics ─────────────────────────────────────────────────────────
    /// <summary>Total errors across all subsystems (tagged by subsystem).</summary>
    public static readonly Counter<long> Errors =
        Meter.CreateCounter<long>("errors.total",
            description: "Total errors (tagged by subsystem and error_type)");
}
